// =============================================================================
// Guardrails — main entry point for the safety layer
// =============================================================================
// Takes a raw LLM response and applies every safety check before the output
// is allowed to reach the user. If any check fails the system returns a
// structured RefusalResponse instead.
// =============================================================================

import type {
  Citation,
  CertaintyLevel,
  CertaintyScore,
  LegalResponse,
  RefusalResponse,
  SafetyConfig,
  SafetyNote,
  Jurisdiction,
} from '@nyayasetu/shared-types';

import { checkForAdvisoryLanguage } from './language-checker.js';
import {
  refuseNoSources,
  refuseLowCertainty,
  STANDARD_DISCLAIMER,
} from './refusal.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Input bundle handed to {@link applyGuardrails}. */
export interface GuardrailInput {
  /** Raw text generated by the LLM. */
  rawResponse: string;
  /** Citations the retrieval pipeline associated with the response. */
  citations: Citation[];
  /** Certainty score produced by the retrieval / ranking step (0-1). */
  certaintyScore: CertaintyScore;
  /** Jurisdiction resolved during entity extraction. */
  jurisdiction: Jurisdiction;
}

/** Return type of {@link applyGuardrails}. */
export type GuardrailOutput = LegalResponse | RefusalResponse;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Map a numeric certainty score to a discrete {@link CertaintyLevel}.
 */
export function calculateCertaintyLevel(score: CertaintyScore): CertaintyLevel {
  if (score >= 0.8) return 'high';
  if (score >= 0.5) return 'medium';
  return 'low';
}

/**
 * Strip detected advisory phrases from the response text.
 *
 */
export function stripAdvisoryLanguage(
  text: string,
  phrases: string[],
): string {
  let cleaned = text;
  for (const phrase of phrases) {
    const escaped = phrase.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(`\\b${escaped}\\b`, 'gi');

    // Rephrase common patterns instead of blanking them
    const lower = phrase.toLowerCase();
    const replacement = REPHRASE_MAP[lower];
    if (replacement !== undefined) {
      cleaned = cleaned.replace(regex, replacement);
    }
  }
  return cleaned;
}

/** Map advisory phrases to neutral informational replacements. */
const REPHRASE_MAP: Record<string, string> = {
  'you should': 'a person in this situation may',
  'you must': 'the law requires that a person',
  'you need to': 'it may be necessary to',
  'you have to': 'a person is required to',
  'you ought to': 'it may be relevant to',
  'you are required to': 'a person is required to',
  'you are advised to': 'it may be relevant to',
  'i advise you': 'the legal position indicates',
  'i recommend': 'the relevant provision states',
  'i suggest': 'one option under the law is',
  'hire a lawyer': 'consult a qualified legal professional',
  'get a lawyer': 'consult a qualified legal professional',
  'make sure to': 'it is important that',
  'ensure that you': 'the law requires that',
  "don't forget to": 'it is important to note that',
  'do not forget to': 'it is important to note that',
};

/**
 * Build the standard de-escalation safety note that is appended to every
 * successful response.
 */
function buildSafetyNote(): SafetyNote {
  return {
    text:
      'If you feel you are in immediate danger or your rights are being violated, ' +
      'please contact local authorities or a legal aid helpline immediately.',
    isDeescalation: true,
  };
}

// ---------------------------------------------------------------------------
// Main guardrail function
// ---------------------------------------------------------------------------

/**
 * Apply all safety guardrails to a raw LLM response.
 *
 * Checks are applied in the following order:
 * 1. **Source availability** -- refuse if no citations and config requires them.
 * 2. **Certainty threshold** -- refuse if the score is below the threshold.
 * 3. **Advisory language** -- strip any directive phrases detected.
 * 4. **Disclaimer & safety note** -- always appended.
 *
 * @returns A verified {@link LegalResponse} or a {@link RefusalResponse}.
 */
export function applyGuardrails(
  input: GuardrailInput,
  config: SafetyConfig,
): GuardrailOutput {
  const { rawResponse, citations, certaintyScore, jurisdiction } = input;

  // 1. Refuse when no sources are available and the config demands sources.
  if (config.refuseOnNoSource && citations.length === 0) {
    return refuseNoSources();
  }

  // 2. Refuse when certainty is below the configured threshold.
  if (certaintyScore < config.certaintyThreshold) {
    return refuseLowCertainty(certaintyScore);
  }

  // 3. Check for advisory language and strip it.
  const advisoryResult = checkForAdvisoryLanguage(rawResponse);
  let safeText = rawResponse;
  if (advisoryResult.containsAdvisoryLanguage) {
    safeText = stripAdvisoryLanguage(rawResponse, advisoryResult.advisoryPhrases);
  }

  // 4. Build the verified response with disclaimer and safety note.
  const certaintyLevel = calculateCertaintyLevel(certaintyScore);

  const response: LegalResponse = {
    type: 'success',
    legalBasis: safeText,
    citations,
    safetyNote: buildSafetyNote(),
    certaintyScore,
    certaintyLevel,
    jurisdiction,
    disclaimer: STANDARD_DISCLAIMER,
  };

  return response;
}
